Consider the given dataset Students Performance Test1
1. Check that is there any missing values in dataframe as a whole
2. is there any missing values across each column
3. count of missing values across each column
4. count row wise missing value
5. count of missing values of a gender column.
6. groupby count of missing values of a column , consider column gender and score
7. replace the missing value of score column with average value of the column

In [ ]:
import pandas as pd
import numpy as np

In [3]:
db=pd.read_csv("/content/drive/MyDrive/DSBDAL_Exam/StudentsPerformanceTest1.csv")

In [5]:
db

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72,72,74.0,78.0,1,Pune
1,female,69,90,88.0,NaN,2,na
2,female,90,95,93.0,74.0,2,Nashik
3,male,47,57,NaN,78.0,1,Na
4,male,na,78,75.0,81.0,3,Pune
5,female,71,Na,78.0,70.0,4,na
6,male,12,44,52.0,12.0,2,Nashik
7,male,NaN,65,67.0,49.0,1,Pune
8,male,5,77,89.0,55.0,0,NaN

In [9]:
# Check if there are any missing values in the dataframe as a whole
print("Any missing values in the dataframe as a whole:", db.isnull().values.any())

Any missing values in the dataframe as a whole: True

In [6]:
db.isnull()

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False
7,False,True,False,False,False,False,False
8,False,False,False,False,False,False,True

In [10]:
# Check if there are any missing values across each column
print("\nMissing values across each column:")
print(db.isnull().sum())

Missing values across each column:
gender                   0
math score               1
reading score            0
writing score            1
Placement Score          1
placement offer count    0
Region                   1
dtype: int64

In [12]:
# Count of missing values across each column
print("\nCount of missing values across each column:")
print(db.isnull().sum())

Count of missing values across each column:
gender                   0
math score               1
reading score            0
writing score            1
Placement Score          1
placement offer count    0
Region                   1
dtype: int64

In [16]:
# Count row-wise missing values
print("\nCount of missing values row-wise:")
print(db.isnull().sum(axis=1))

Count of missing values row-wise:
0    0
1    1
2    0
3    1
4    0
5    0
6    0
7    1
8    1
dtype: int64

In [18]:
# Count of missing values in the 'gender' column
print("\nCount of missing values in the 'gender' column:", db['gender'].isnull().sum())

Count of missing values in the 'gender' column: 0

In [22]:
# Groupby count of missing values of a column, considering columns 'gender' and 'score'
print("\nGroupby count of missing values of 'gender', 'Placement Score','writing score','reading score' and 'math score' columns:")
print(db.groupby(['gender', 'Placement Score','writing score','reading score','math score']).size().unstack(fill_value=0))

Groupby count of missing values of 'gender', 'Placement Score','writing score','reading score' and 'math score' columns:
math score                                          71  90  72  12  5  na
gender Placement Score writing score reading score
female 70.0            78.0          Na              1   0   0   0  0   0
       74.0            93.0          95              0   1   0   0  0   0
       78.0            74.0          72              0   0   1   0  0   0
male   12.0            52.0          44              0   0   0   1  0   0
       55.0            89.0          77              0   0   0   0  1   0
       81.0            75.0          78              0   0   0   0  0   1

In [23]:
db

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72,72,74.0,78.0,1,Pune
1,female,69,90,88.0,NaN,2,na
2,female,90,95,93.0,74.0,2,Nashik
3,male,47,57,NaN,78.0,1,Na
4,male,na,78,75.0,81.0,3,Pune
5,female,71,Na,78.0,70.0,4,na
6,male,12,44,52.0,12.0,2,Nashik
7,male,NaN,65,67.0,49.0,1,Pune
8,male,5,77,89.0,55.0,0,NaN

In [43]:
db.replace('Na','NaN', inplace=True)

In [44]:
db

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72,72,74.0,78.0,1,Pune
1,female,69,90,88.0,NaN,2,NaN
2,female,90,95,93.0,74.0,2,Nashik
3,male,47,57,NaN,78.0,1,NaN
4,male,NaN,78,75.0,81.0,3,Pune
5,female,71,NaN,78.0,70.0,4,NaN
6,male,12,44,52.0,12.0,2,Nashik
7,male,NaN,65,67.0,49.0,1,Pune
8,male,5,77,89.0,55.0,0,NaN

In [58]:
# Calculate average score excluding NaN values
average_score = db['writing score'].mean(skipna=True)
print("Avg Writing Score",average_score)
db['writing score'].fillna(average_score, inplace=True)
print("\n",db)

Avg Writing Score 77.0

    gender math score reading score  writing score  Placement Score  \
0  female         72            72           74.0             78.0
1  female         69            90           88.0              NaN
2  female         90            95           93.0             74.0
3    male         47            57           77.0             78.0
4    male        NaN            78           75.0             81.0
5  female         71           NaN           78.0             70.0
6    male         12            44           52.0             12.0
7    male        NaN            65           67.0             49.0
8    male          5            77           89.0             55.0

   placement offer count  Region
0                      1    Pune
1                      2     NaN
2                      2  Nashik
3                      1     NaN
4                      3    Pune
5                      4     NaN
6                      2  Nashik
7                      1    Pune
8                      0     NaN

In [59]:
# Calculate average score excluding NaN values
average_score = db['writing score'].mean(skipna=True)
print("Avg Placement Score",average_score)
db['Placement Score'].fillna(average_score, inplace=True)
print("\n",db)

Avg Placement Score 77.0

    gender math score reading score  writing score  Placement Score  \
0  female         72            72           74.0             78.0
1  female         69            90           88.0             77.0
2  female         90            95           93.0             74.0
3    male         47            57           77.0             78.0
4    male        NaN            78           75.0             81.0
5  female         71           NaN           78.0             70.0
6    male         12            44           52.0             12.0
7    male        NaN            65           67.0             49.0
8    male          5            77           89.0             55.0

   placement offer count  Region
0                      1    Pune
1                      2     NaN
2                      2  Nashik
3                      1     NaN
4                      3    Pune
5                      4     NaN
6                      2  Nashik
7                      1    Pune
8                      0     NaN

In [67]:
db['math score'] = db['math score'].astype(float).round(1)
db['reading score'] = db['reading score'].astype(float).round(1)

In [68]:
# Calculate average score excluding NaN values
average_score = db['math score'].mean(skipna=True)
print("Avg Placement Score",average_score)
db['math score'].fillna(average_score, inplace=True)
print("\n",db)

Avg Placement Score 52.28888888888889

    gender  math score  reading score  writing score  Placement Score  \
0  female        72.0           72.0           74.0             78.0
1  female        69.0           90.0           88.0             77.0
2  female        90.0           95.0           93.0             74.0
3    male        47.0           57.0           77.0             78.0
4    male        52.3           78.0           75.0             81.0
5  female        71.0            NaN           78.0             70.0
6    male        12.0           44.0           52.0             12.0
7    male        52.3           65.0           67.0             49.0
8    male         5.0           77.0           89.0             55.0

   placement offer count  Region
0                      1    Pune
1                      2     NaN
2                      2  Nashik
3                      1     NaN
4                      3    Pune
5                      4     NaN
6                      2  Nashik
7                      1    Pune
8                      0     NaN