1. Load the MallCustomer dataset in dataframe object df
2. Display summary statistics (mean, median, minimum, maximum, standard deviation) for
a dataset for each column
3. Display Measures of Dispersion ( Mean Absolute Deviation, Variance, Standard Deviation,
Range, Quartiles, Skewness)
4. if your categorical variable is age groupsa nd quantitative variable is income, then
provide summary statistics (minimum and maximum) of income grouped by the age
groups.

In [2]:
import pandas as pd
import numpy as np

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
data=pd.read_csv("/content/drive/MyDrive/DSBDAL_Exam/Mall_Customers.csv")

In [5]:
data

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [6]:
df=data

In [7]:
# Step 2: Display summary statistics for each column
df.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [17]:
# Calculate measures of dispersion for each quantitative variable
mad = df[["Age", "Annual Income (k$)"]].apply(np.abs).mean()
variance = df[["Age", "Annual Income (k$)"]].var()
std_dev = df[["Age", "Annual Income (k$)"]].std()
range = df[["Age", "Annual Income (k$)"]].max() - df[["Age", "Annual Income (k$)"]].min()
quartiles = df[["Age", "Annual Income (k$)"]].quantile([0.25, 0.5, 0.75])
skewness = df[["Age", "Annual Income (k$)"]].skew()

In [21]:
# Calculate summary statistics for income by age group
grouped_df = df.groupby("Age")["Annual Income (k$)"].agg(["min", "max", "mean", "median"])

In [23]:
# Print the results
print("\nMeasures of Dispersion:")
print(f"Mean Absolute Deviation:\n{mad}")
print(f"\nVariance:\n{variance}")
print(f"\nStandard Deviation:\n{std_dev}")
print(f"\nRange:\n{range}")
print(f"\nQuartiles:\n{quartiles}")
print(f"\nSkewness:\n{skewness}")

Measures of Dispersion:
Mean Absolute Deviation:
Age                   38.85
Annual Income (k$)    60.56
dtype: float64

Variance:
Age                   195.133166
Annual Income (k$)    689.835578
dtype: float64

Standard Deviation:
Age                   13.969007
Annual Income (k$)    26.264721
dtype: float64

Range:
Age                    52
Annual Income (k$)    122
dtype: int64

Quartiles:
        Age  Annual Income (k$)
0.25  28.75                41.5
0.50  36.00                61.5
0.75  49.00                78.0

Skewness:
Age                   0.485569
Annual Income (k$)    0.321843
dtype: float64

In [26]:
# Create new age categories
df["Age Category"] = pd.cut(df["Age"], bins=[18, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70], labels=["18-25", "25-30", "30-35", "35-40", "40-45", "45-50", "50-55", "55-60", "60-65", "65-70"])

In [30]:
# Group data by age category and calculate summary statistics for income
grouped_df = df.groupby("Age Category")["Annual Income (k$)"].agg(["min", "max"])

In [31]:
# Print the results
print("\nSummary Statistics for Income by Age Category:")
print(grouped_df.to_string())

Summary Statistics for Income by Age Category:
              min  max
Age Category
18-25          15   81
25-30          19  137
30-35          17  137
35-40          20  113
40-45          28  126
45-50          25  120
50-55          23  101
55-60          20   93
60-65          19   65
65-70          19   63